CELL_SIZE = 80
MAP_ROWS = 6
MAP_COLS = 8
TEXTBOARD_WIDTH = 162
GAMEBOARD_WIDTH = MAP_COLS*CELL_SIZE
SCREEN_WIDTH = GAMEBOARD_WIDTH + TEXTBOARD_WIDTH
TEXTBOARD_HEIGHT = GAMEBOARD_HEIGHT = SCREEN_HEIGHT = MAP_ROWS*CELL_SIZE

STEP = 80


games = {}
def get_game():
    return games.get('DEFAULTGAME')